# Generated by Django 4.1.2 on 2023-10-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_booking_myclass_mymodel_delete_mehsul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='product',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
