# Generated by Django 4.1.2 on 2023-10-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_booking_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='total',
            new_name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
